
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author javie
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_Titulo = new javax.swing.JLabel();
        Btt_Saludar = new javax.swing.JButton();
        Txt_Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        Lbl_Titulo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 48)); // NOI18N
        Lbl_Titulo.setForeground(new java.awt.Color(255, 102, 0));
        Lbl_Titulo.setText("Ejemplo");
        jPanel1.add(Lbl_Titulo);
        Lbl_Titulo.setBounds(10, 20, 180, 70);

        Btt_Saludar.setText("Saludar");
        Btt_Saludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_SaludarActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Saludar);
        Btt_Saludar.setBounds(560, 150, 140, 50);
        jPanel1.add(Txt_Nombre);
        Txt_Nombre.setBounds(30, 150, 220, 50);

        Tabla_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Columna 1", "Columna 2"
            }
        ));
        Tabla_Datos.setRowHeight(40);
        jScrollPane1.setViewportView(Tabla_Datos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 660, 403);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btt_SaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_SaludarActionPerformed
        //JOptionPane mensaje = new JOptionPane("Hola");
        String nombreUsuario = Txt_Nombre.getText();
        JOptionPane.showMessageDialog(null, "Hola 1" + nombreUsuario);
        
        Txt_Nombre.setText("");
        
        //CREAMOS EL ARREGLO
        Datos[] datos = new Datos[5];
        //LLENAMOS EL ARREGLO
        datos[0] = new Datos("Nombre1", 11);
        datos[1] = new Datos("Nombre2", 12);
        datos[2] = new Datos("Nombre3", 13);
        datos[3] = new Datos("Nombre4", 14);
        datos[4] = new Datos("Nombre5", 15);
        
        //CONVERTIR ARREGLO A MATRIZ
        String[][] matriz = new String[datos.length][2];
        for (int i = 0; i < datos.length; i++) {
            matriz[i][0] = datos[i].getNombre();
            matriz[i][1] = Integer.toString(datos[i].getEdad());
        }
        
        //IMPRIMIR MATRIZ EN CONSOLA
        for (int i = 0; i < datos.length; i++) {
            System.out.println("");
            for (int j = 0; j < 2; j++) {
                System.out.print(matriz[i][j] + " ");
            }
        }
        
        //PASAR DATOS DE MATRIZ A TABLA
        String[] encabezado = {"Nombre", "Edad"};
        Tabla_Datos.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));
        
        
        
        /*
        Frame2 frame2 = new Frame2();
        frame2.setVisible(true);
        this.setVisible(false);
        */
        
    }//GEN-LAST:event_Btt_SaludarActionPerformed

    //ACA PONGO MIS DATOS DE INICIO
    private void initComponents2(){
        setLocationRelativeTo(null);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_Saludar;
    private javax.swing.JLabel Lbl_Titulo;
    private javax.swing.JTable Tabla_Datos;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
