
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author javie
 */
public class Frame2 extends javax.swing.JFrame {

    private static Usuario[] listaUsuarios = new Usuario[2];

    public Frame2() {
        initComponents();
        initComponents2();
    }

    private void initComponents2() {
        setLocationRelativeTo(null);
    }

    private Usuario[] redimensionarArreglo(Usuario[] arreglo) {
        Usuario[] temporal = new Usuario[arreglo.length + 1];
        for (int i = 0; i < arreglo.length; i++) {
            temporal[i] = arreglo[i];
        }
        return temporal;
    }

    private Boolean hayEspacio(Usuario[] arreglo) {
        Boolean espacio = false;
        for (int i = 0; i < arreglo.length; i++) {
            if (arreglo[i] == null) {
                espacio = true;
                break;
            }
        }
        return espacio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt_Usuario = new javax.swing.JTextField();
        Txt_Password = new javax.swing.JPasswordField();
        Btt_Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Principal = new javax.swing.JTable();
        Btt_Regresar = new javax.swing.JButton();
        Btt_Refrescar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btt_Eliminar = new javax.swing.JButton();
        Btt_Reportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);
        jPanel1.add(Txt_Usuario);
        Txt_Usuario.setBounds(80, 150, 390, 40);
        jPanel1.add(Txt_Password);
        Txt_Password.setBounds(80, 210, 390, 40);

        Btt_Agregar.setText("Agregar");
        Btt_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Agregar);
        Btt_Agregar.setBounds(530, 170, 230, 60);

        Table_Principal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_Principal);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 360, 660, 200);

        Btt_Regresar.setText("Regresar");
        Btt_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Regresar);
        Btt_Regresar.setBounds(640, 630, 110, 40);

        Btt_Refrescar.setText("Refrescar");
        Btt_Refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_RefrescarActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Refrescar);
        Btt_Refrescar.setBounds(550, 310, 200, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 102));
        jLabel1.setText("Registro");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 180, 70);

        Btt_Eliminar.setText("Eliminar");
        Btt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Eliminar);
        Btt_Eliminar.setBounds(630, 570, 120, 50);

        Btt_Reportar.setText("Reportar");
        Btt_Reportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btt_ReportarActionPerformed(evt);
            }
        });
        jPanel1.add(Btt_Reportar);
        Btt_Reportar.setBounds(90, 590, 190, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btt_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_AgregarActionPerformed
        //Se verifica si hay que redimensionar el arreglo
        if (!hayEspacio(listaUsuarios)) {
            System.out.println("Tamaño Actual: " + getListaUsuarios().length);
            listaUsuarios = redimensionarArreglo(getListaUsuarios());
            System.out.println("Tamaño Nuevo: " + getListaUsuarios().length);
        }

        //Se busca una posicion vacia para agrear al suario
        for (int i = 0; i < getListaUsuarios().length; i++) {
            if (getListaUsuarios()[i] == null) {
                listaUsuarios[i] = new Usuario(Txt_Usuario.getText(), Txt_Password.getText());
                break;
            }
        }

        Txt_Usuario.setText("");
        Txt_Password.setText("");
    }//GEN-LAST:event_Btt_AgregarActionPerformed

    private void Btt_RefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_RefrescarActionPerformed
        for (int i = 0; i < getListaUsuarios().length; i++) {
            if (getListaUsuarios()[i] != null) {
                System.out.println("********");
                System.out.println(getListaUsuarios()[i].getNombreUsuario());
                System.out.println(getListaUsuarios()[i].getPassword());
                System.out.println("********");
            }
        }

        //PASAR DATOS A MATRIZ
        String[][] matriz = new String[getListaUsuarios().length][2];
        for (int i = 0; i < getListaUsuarios().length; i++) {
            if (getListaUsuarios()[i] != null) {
                matriz[i][0] = getListaUsuarios()[i].getNombreUsuario();
                matriz[i][1] = getListaUsuarios()[i].getPassword();
            }
        }

        //PASAR DATOS DE MATRIZ A TABLA
        String[] encabezado = {"Usuario", "Password"};
        Table_Principal.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));
    }//GEN-LAST:event_Btt_RefrescarActionPerformed

    private void Btt_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_RegresarActionPerformed
        Frame1 f1 = new Frame1();
        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Btt_RegresarActionPerformed

    private void Btt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_EliminarActionPerformed
        for (int i = 0; i < getListaUsuarios().length; i++) {
            if (getListaUsuarios()[i] != null) {
                if (getListaUsuarios()[i].getNombreUsuario().equals(Txt_Usuario.getText())) {
                    getListaUsuarios()[i] = null;
                }
            }
        }
    }//GEN-LAST:event_Btt_EliminarActionPerformed

    private void Btt_ReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btt_ReportarActionPerformed
        String cadenaHTML = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte</title>\n"
                + "</head>\n"
                + "<body>\n"
                + "<table>\n"
                + "        <tr>"
                + "          <th>Nombre Usuario</th>\n"
                + "          <th>Password</th>\n"
                + "        </tr>";

        for (int i = 0; i < getListaUsuarios().length; i++) {
            if (getListaUsuarios()[i] != null) {
                cadenaHTML += "<tr>";
                cadenaHTML += "  <td>" + getListaUsuarios()[i].getNombreUsuario() + "</td>";
                cadenaHTML += "  <td>" + getListaUsuarios()[i].getPassword()+ "</td>";
                cadenaHTML += "</tr>";
            }
        }

        cadenaHTML += "      </table>\n"
                + "</body>\n"
                + "</html>";

        File archivo = new File("reporte.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));
            bw.write(cadenaHTML);
            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Btt_ReportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btt_Agregar;
    private javax.swing.JButton Btt_Eliminar;
    private javax.swing.JButton Btt_Refrescar;
    private javax.swing.JButton Btt_Regresar;
    private javax.swing.JButton Btt_Reportar;
    private javax.swing.JTable Table_Principal;
    private javax.swing.JPasswordField Txt_Password;
    private javax.swing.JTextField Txt_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the listaUsuarios
     */
    public static Usuario[] getListaUsuarios() {
        return listaUsuarios;
    }
}
